### ISSUE TITLE
✨ FEAT. 맞춤형 식단 추천 기능 구현

### ISSUE THREAD

**Issue by junhaa** [2024-tantanmen/Backend#4]
# 📝 Preview

✨ FEAT. 맞춤형 식단 추천 기능 구현

# ✅ Todo
- [x]  알레르기, 식습관 반영 맞춤형 식단 추천
- [x]  음식 데이터 구성성분으로 추가
- [x]  맟춤형 식단 추천 알고리즘 구현

# 📌 Remark
