### ISSUE TITLE
✨ FEAT. 음식 사진 인식 기능 구현

### ISSUE THREAD

**Issue by junhaa** [2024-tantanmen/Backend#7]
# 📝 Preview

✨ FEAT. 음식 사진 인식 기능 구현

# ✅ Todo
- [x]  Yolov3 사진 인식 모델 => 사진 데이터 AI Hub (60만장)
- [x]  파이썬 docker 컨테이너로 구축 (or 인스턴스 따로)
- [x]  음식 별 탄수화물, 단백질, 지질 함량 데이터 추가

# 📌 Remark
